version: '3.9'

services:
  nos2x-dev:
    image: nos2x-dev
    container_name: nos2x-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /nos2x
    volumes:
      - ..:/nos2x:cached
    tty: true